name: weather_app_lab4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.2

  flutter_map: ^6.0.0
  latlong2: 0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
